### ISSUE TITLE
Plugin failed to start in folia 1.20.1 (7c6e251)

### ISSUE THREAD

**Issue by eternitymoe** [Folium-MC/CMILib#1]
Stack Trace:
> [00:55:11] [Server thread/INFO]: [CMILib] Enabling CMILib v1.3.0.2
> [00:55:12] [Server thread/INFO]: Server version: v1_20_R1 - 1.20.1 - paper
> [00:55:12] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/world/level/World
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Reflections.initialize(Reflections.java:128)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Reflections.<init>(Reflections.java:121)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:79)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:90)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.CMILib.onEnable(CMILib.java:192)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
> [00:55:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
> [00:55:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:679)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:463)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346)
> [00:55:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
> [00:55:12] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.World
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
> [00:55:12] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> [00:55:12] [Server thread/WARN]: 	... 17 more
> [00:55:12] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.network.PlayerConnection
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
> [00:55:12] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> [00:55:12] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
> [00:55:12] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Reflections.initialize(Reflections.java:136)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Reflections.<init>(Reflections.java:121)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:79)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:90)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.CMILib.onEnable(CMILib.java:192)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
> [00:55:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
> [00:55:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:679)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:463)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346)
> [00:55:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
> [00:55:12] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/nbt/NBTBase
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.NBT.CMINBT.<clinit>(CMINBT.java:109)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Reflections.asNMSCopy(Reflections.java:1028)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Reflections.getItemMinecraftName(Reflections.java:841)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:90)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.CMILib.onEnable(CMILib.java:192)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
> [00:55:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
> [00:55:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:679)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:463)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346)
> [00:55:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
> [00:55:12] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.nbt.NBTBase
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
> [00:55:12] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> [00:55:12] [Server thread/WARN]: 	... 17 more
> [00:55:12] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getMethod(String, java.lang.Class[])" because "net.Zrips.CMILib.NBT.CMINBT.nbtTagCompound" is null
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.NBT.CMINBT.<clinit>(CMINBT.java:233)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Reflections.asNMSCopy(Reflections.java:1028)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Reflections.getItemMinecraftName(Reflections.java:841)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:90)
> [00:55:12] [Server thread/WARN]: 	at CMILib-1.3.0.2.jar//net.Zrips.CMILib.CMILib.onEnable(CMILib.java:192)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
> [00:55:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
> [00:55:12] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
> [00:55:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:679)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:463)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188)
> [00:55:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346)
> [00:55:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
> [00:55:13] [Server thread/ERROR]: Error occurred while enabling CMILib v1.3.0.2 (Is it up to date?)
> java.lang.NullPointerException: Cannot invoke "java.lang.Class.cast(Object)" because "this.CraftWorldClass" is null
> 	at net.Zrips.CMILib.Reflections.getCraftWorld(Reflections.java:769) ~[CMILib-1.3.0.2.jar:?]
> 	at net.Zrips.CMILib.Reflections.getServerName(Reflections.java:758) ~[CMILib-1.3.0.2.jar:?]
> 	at net.Zrips.CMILib.commands.CommandsHandler.<init>(CommandsHandler.java:59) ~[CMILib-1.3.0.2.jar:?]
> 	at net.Zrips.CMILib.CMILib.getCommandManager(CMILib.java:111) ~[CMILib-1.3.0.2.jar:?]
> 	at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:208) ~[CMILib-1.3.0.2.jar:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
> 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
> 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
> 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
> 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:679) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
> 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:463) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
> 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> [00:55:13] [Server thread/INFO]: [CMILib] Disabling CMILib v1.3.0.2

Folia version:  git-Folia-"7c6e251" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 7c6e251)

**Comment by eternitymoe** [comment]
Ignore this as it caused by a mistake compilation
